image: golang

stages:
  - lint
  - build
  - deploy

lint:
  stage: lint
  script:
    - go get github.com/golang/lint/golint
    - go list ./... | grep -v vendor | xargs -n1 golint --set_exit_status

binaries:
  stage: build
  script:
    - go get github.com/mitchellh/gox
    - make cross
  artifacts:
    paths:
      - out/
