image: golang

stages:
  - lint
  - build

before_script:
  - mkdir -p $GOPATH/src/git.practool.xyz/nova
  - ln -s $(pwd) $GOPATH/src/git.practool.xyz/nova/goJASM
  - cd $GOPATH/src/git.practool.xyz/nova/goJASM
  - go get github.com/Masterminds/glide
  - glide install

lint:
  stage: lint
  script:
    - go get github.com/golang/lint/golint
    - go list ./... | grep -v vendor | xargs -n1 golint --set_exit_status
  tags:
    - k8s

.binaries: &binaries
  stage: build
  script:
  - export PLATFORMS=$(echo $CI_JOB_NAME | sed 's|binaries ||')
  - go get github.com/mitchellh/gox
  - gox -osarch="$PLATFORMS" -output="out/gojasm-{{.OS}}-{{.Arch}}"
  artifacts:
    paths:
    - out/
  tags:
    - k8s

binaries darwin/386 darwin/amd64: *binaries
binaries linux/386 linux/amd64 linux/arm: *binaries
binaries windows/386 windows/amd64: *binaries