image: golang

stages:
  - lint
  - build
  - deploy

before_script:
  - mkdir -p $GOPATH/src/git.practool.xyz/nova
  - ln -s $(pwd) $GOPATH/src/git.practool.xyz/nova/goJASM
  - cd $GOPATH/src/git.practool.xyz/nova/goJASM
  - go get github.com/Masterminds/glide
  - glide install

lint:
  stage: lint
  script:
    - go get github.com/golang/lint/golint
    - go list ./... | grep -v vendor | xargs -n1 golint --set_exit_status

.binaries: &binaries
  stage: build
  script:
  - export PLATFORMS=$(echo $CI_JOB_NAME | sed 's|binaries ||')
  - go get github.com/mitchellh/gox
  - gox -osarch="$PLATFORMS" -output="out/gojasm-{{.OS}}-{{.Arch}}"
  artifacts:
    paths:
    - out/

deploy:
  stage: deploy
  only:
   - tags
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - scp -Br out/ deploy@phoenix.labs.vu.nl:files/gojasm/

binaries darwin/386 darwin/amd64: *binaries
binaries linux/386 linux/amd64 linux/arm: *binaries
binaries windows/386 windows/amd64: *binaries